language: 
  - node_js

node_js:
  - lts/*

services:
  - docker

before_install:
  - docker build -t testimage  -f Dockerfile.dev .

script:
  - docker run testimage -e CI=true npm run test -- --coverage 
